name: Deploy Homolog

# O gatilho (evento) será a atualização (push) direta na branch homolog
on:
  push:
    branches:
      - homolog

jobs:
  deploy:
    runs-on: self-hosted # Informa ao GitHub para rodar no seu Windows 11
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Baixa o código do repositório
      
      - name: Atualizar Container Docker Local
        # Usando o Docker Compose, um único comando faz todo o ciclo de build e restart
        run: docker compose up -d --build