name: Deploy Homolog

on:
  push:
    branches:
      - homolog

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Atualizar Container Docker Local
        shell: cmd # <--- Isso força o uso do CMD do Windows
        run: docker compose up -d --build