name: Deploy Homolog
# O gatilho (evento) será a atualização (push) direta na branch homolog
on:
  push:
    branches:
      - homolog

jobs:
  deploy:
    runs-on: self-hosted # Informa ao GitHub para rodar no seu Windows 11
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Baixa o código do repositório
      
      - name: Atualizar Container Docker Local
        # Aqui você insere os comandos que rodam no seu Windows
        run: |
          docker build -t maestro-homolog .
          docker stop maestro-homolog-container || true
          docker rm maestro-homolog-container || true
          docker run -d -p 3000:3000 --name maestro-homolog-container maestro-homolog
          