name: Rollback Homolog

on:
  workflow_dispatch:
    inputs:
      target_commit:
        description: 'SHA do Commit (Deixe em branco para voltar para a versão anterior)'
        required: false
        default: '' # Começa vazio por padrão

jobs:
  rollback:
    runs-on: self-hosted
    steps:
      # 1. Baixa sempre a branch homolog com o histórico completo (fetch-depth: 0)
      - name: Checkout do código (Homolog)
        uses: actions/checkout@v4
        with:
          ref: homolog
          fetch-depth: 0

      # 2. Se você deixou em branco, o próprio Git local volta 1 commit no seu PC
      - name: Voltar para o commit anterior (Padrão)
        if: ${{ github.event.inputs.target_commit == '' }}
        shell: cmd
        run: git checkout HEAD~1

      # 3. Se você colou o SHA de um commit, o Git vai direto para ele
      - name: Ir para o commit especificado
        if: ${{ github.event.inputs.target_commit != '' }}
        shell: cmd
        run: git checkout ${{ github.event.inputs.target_commit }}

      # 4. Reconstrói o container com a versão do código que o Git selecionou acima
      - name: Reverter Container Docker Local
        shell: cmd
        run: docker compose up -d --build